mappings:
  SSEmbedableGalleryLeftAndMainExtension: CatchDesign\EmbedableGallery\Extensions\SSEmbedableGalleryLeftAndMainExtension
  SSEmedableGalleryPageExtension: CatchDesign\EmbedableGallery\Extensions\SSEmedableGalleryPageExtension
  SSEmbedableGalleryEmbedLinkExtension: CatchDesign\EmbedableGallery\Extensions\SSEmbedableGalleryEmbedLinkExtension
  MediaPageAdmin: CatchDesign\EmbedableGallery\ModelAdmin\MediaPageAdmin
  VideoPage: CatchDesign\EmbedableGallery\SiteTree\VideoPage
  VideoPage_Controller: CatchDesign\EmbedableGallery\SiteTree\VideoPage_Controller
  AlbumPage: CatchDesign\EmbedableGallery\SiteTree\AlbumPage
  AlbumPage_Controller: CatchDesign\EmbedableGallery\SiteTree\AlbumPage_Controller
  ImagesHolder: CatchDesign\EmbedableGallery\SiteTree\ImagesHolder
  ImagesHolder_Controller: CatchDesign\EmbedableGallery\SiteTree\ImagesHolder_Controller
  MediaPage: CatchDesign\EmbedableGallery\SiteTree\MediaPage
  MediaPage_Controller: CatchDesign\EmbedableGallery\SiteTree\MediaPage_Controller
  VideosHolder: CatchDesign\EmbedableGallery\SiteTree\VideosHolder
  VideosHolder_Controller: CatchDesign\EmbedableGallery\SiteTree\VideosHolder_Controller
  ImagePage: CatchDesign\EmbedableGallery\SiteTree\ImagePage
  ImagePage_Controller: CatchDesign\EmbedableGallery\SiteTree\ImagePage_Controller
  AlbumsHolder: CatchDesign\EmbedableGallery\SiteTree\AlbumsHolder
  AlbumsHolder_Controller: CatchDesign\EmbedableGallery\SiteTree\AlbumsHolder_Controller
  MediaHomePage: CatchDesign\EmbedableGallery\SiteTree\MediaHomePage
  MediaHomePage_Controller: CatchDesign\EmbedableGallery\SiteTree\MediaHomePage_Controller
  AlbumAdmin: CatchDesign\EmbedableGallery\Controllers\AlbumAdmin