name: SSEmbedableGallery
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - SSEmbedableGalleryLeftAndMainExtension
CatchDesign\EmbedableGallery\SiteTree:
  extensions:
    - SSEmedableGalleryPageExtension
