---
name: SSEmbedableGallery
After:
  - '#core'
  - '#versionedgridfield'
  - '#requestprocessors'
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - CatchDesign\EmbedableGallery\Extensions\SSEmbedableGalleryLeftAndMainExtension

CatchDesign\EmbedableGallery\SiteTree:
  extensions:
    - CatchDesign\EmbedableGallery\Extensions\SSEmedableGalleryPageExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\Versioned\VersionedGridFieldItemRequest:
    class: CatchDesign\EmbedableGallery\Gridfield\VersionedGridFieldItemRequest

